config/routes.rb
Rails.application.routes.draw do
  root "courses#index"
  get "courses/new", to: "courses#new"
  get "about", to: "pages#about"
  resources :students, except: [:destroy]
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"
  post "course_enroll", to: "student_courses#create"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
  validates :name, presence: true, length: { minimum: 5, maximum: 50 }
  validates :short_name, presence: true, length: { minimum: 3, maximum: 15 }
  validates :description, presence: true, length: { minimum: 10, maximum: 300 }

  has_many :student_courses
  has_many :students, through: :student_courses
end

app/models/student.rb
class Student < ApplicationRecord
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { minimum: 5, maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :email, presence: true,
                    uniqueness: { case_sensitive: false },
                    length: { maximum: 105 },
                    format: { with: VALID_EMAIL_REGEX }

  has_secure_password

  has_many :student_courses
  has_many :courses, through: :student_courses
end

app/models/student_course.rb
class StudentCourse < ApplicationRecord
  belongs_to :student
  belongs_to :course
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :require_user

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= Student.find(session[:student_id]) if session[:student_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:notice] = "You must be login to perform that action"
      redirect_to login_path
    end
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  skip_before_action :require_user

  def index
    @courses = Course.all
  end

  def new
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :require_user

  def about
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_user, only: [:new, :create]

  def new
  end

  def create
    @student = Student.find_by(email: params[:sessions][:email].downcase)
    if @student && @student.authenticate(params[:sessions][:password])
      session[:student_id] = @student.id
      flash[:success] = "You have sucessfully logged in"
      redirect_to @student
    else
      flash.now[:notice] = "Something was wrong with your login information"
      render "new"
    end
  end

  def destroy
    session[:student_id] = nil
    flash[:success] = "You have successfully logged out"
    redirect_to root_path
  end
end

app/controllers/student_courses_controller.rb
class StudentCoursesController < ApplicationController
  def create
    @student = current_user
    @course = Course.find(params[:course_id])
    if @student.courses << @course
      flash[:success] = "Successfully enrolled in the course."
    else
      flash[:error] = "Failed to enroll in the course."
    end
    redirect_to @student
  end

  def destroy
    @student = current_user
    @course = Course.find(params[:id])
    @student.courses.delete(@course)
    flash[:success] = "Successfully unenrolled from the course."
    redirect_to @course
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  skip_before_action :require_user, only: [:new, :create]
  before_action :require_same_student, only: [:edit, :update]

  def index
    @students = Student.all
  end

  def show
    @student = Student.find(params[:id])
  end

  def new
    @student = Student.new
  end

  def create
    @student = Student.new(student_params)
    if @student.save
      flash[:success] = "You have successfully signed up"
      redirect_to root_path
    else
      render "new"
    end
  end

  def edit
    @student = Student.find(params[:id])
  end

  def update
    @student = Student.find(params[:id])

    if @student.update(student_params)
      flash[:success] = "You have successfully updated your profile"
      redirect_to student_path(@student)
    else
      render "edit"
    end
  end

  private

  def student_params
    params.require(:student).permit(:name, :email, :password, :password_confirmation)
  end

  def require_same_student
    if current_user != @student = Student.find(params[:id])
      redirect_to student_path(current_user)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def session_link
    if logged_in?
      link_to "logout", logout_path, method: :delete
    else
      link_to "login", login_path
    end
  end
end

app/views/courses/_courseinfo.html.erb
<% @courses.each do |course|%>
  <div class="col s6 m6">
    <div class="card blue-grey darken-1">
      <div class="card-content white-text">
        <span class="card-title"><%=course.short_name %> : <%= course.name%> </span>
        <p><%= course.description%></p>
      </p>
    </div>
    <div class="card-action">
      <% if logged_in? && !(current_user.courses.include?(course)) %>
        <%= link_to "Enroll", course_enroll_path(course_id: course.id), method: :post %>
      <%end%>
      <a href="#">Info</a>
    </div>
  </div>
</div>
<% end%>

app/views/courses/index.html.erb
<div class="row">
  <div class="col s12">
    <h3 class="center-align" > Course Listing</h3>
  </div>
</div>
<div class="row">
  <%= render 'courseinfo'%>
</div>
<div class="row">
</div>

app/views/courses/new.html.erb
<h1>this is a new course page</h1>

app/views/layouts/_footer.html.erb
<footer class="page-footer grey darken-2 ">
  <div class="container">
    <div class="row">
      <div class="col l6 s12">
        <h5 class="white-text">Tech Uiversity</h5>
        <p class="grey-text text-lighten-4">An investment in knowledge pays the best interest</p>
      </div>
      <div class="col l4 offset-l2 s12">
        <h5 class="white-text">Information</h5>
        <ul>
          <li><a class="grey-text text-lighten-3" href="#!">Help</a></li>
          <li><a class="grey-text text-lighten-3" href="#!">About</a></li>
          <li><a class="grey-text text-lighten-3" href="#!">Contact us</a></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="footer-copyright">
    <div class="container">
      © 2025 Tech University @pravin
      <a class="grey-text text-lighten-4 right" href="#!">About</a>
    </div>
  </div>
</footer>

app/views/layouts/_navbar.html.erb
<ul id="dropdown1" class="dropdown-content">
  <% if logged_in? %>
    <li><%= link_to(student_path(current_user)) { "<i class='material-icons left'>person</i> #{current_user.name[0, 5]}".html_safe } %></li>
    <li class="divider"></li>
    <li><%= link_to "Logout", logout_path, method: :delete %></li>
  <% else %>
    <li><%= link_to "Login", login_path %></li>
    <li class="divider"></li>
    <li><%= link_to "Sign up", new_student_path %></li>
  <% end %>
</ul>
<ul id="dropdown2" class="dropdown-content">
  <% if logged_in? %>
    <li><%= link_to(student_path(current_user)) { "<i class='material-icons left'>person</i> #{current_user.name[0, 5]}".html_safe } %></li>
    <li class="divider"></li>
    <li><%= link_to "Logout", logout_path, method: :delete %></li>
  <% else %>
    <li><%= link_to "Login", login_path %></li>
    <li class="divider"></li>
    <li><%= link_to "Sign up", new_student_path %></li>
  <% end %>
</ul>
<nav class="grey darken-3">
  <div class="container">
    <div class="nav-wrapper  ">
      <a href="#" class="brand-logo right">Tech University</a>
      <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
      <ul id="nav-mobile" class="left hide-on-med-and-down">
        <li> <%= link_to "Courses", root_path %></li>
        <li> <%= link_to "Enrollments", students_path %></li>
        <li><a class="dropdown-trigger" href="#!" data-target="dropdown1">Account<i class="material-icons right">arrow_drop_down</i></a></li>
      </ul>
      <ul class="sidenav" id="mobile-demo">
        <li><a href="#">Courses</a></li>
        <li> <%= link_to "Courses", root_path %></li>
        <li> <%= link_to "Enrollments", students_path %></li>
        <li><a class="dropdown-trigger" href="#!" data-target="dropdown2">Account<i class="material-icons right">arrow_drop_down</i></a></li>
      </ul>
    </div>
  </div>
</nav>
<% flash.each do |type, message| %>
  <div class="container">
    <div class="row sign-up">
      <div class="col s12 m12 l12">
        <div class="card-panel <%= type == 'success' ? 'green lighten-2' : 'red lighten-1' %>" id = "fade-out" >
          <span class="white-text"><%= message %></span>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tech University</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navbar'%>
    </header>
    <main>
      <div class="container">
        <%= yield %>
      </div>
    </main>
    <%= render 'layouts/footer'%>
  </body>
</html>

app/views/pages/about.html.erb
<h1> this is about page.</h1>

app/views/students/_errormessages.html.erb
<% if @student.errors.any?%>
  <div class="container">
    <div class="row sign-up">
      <div class="col s12 m12 l12">
        <div class="card-panel red lighten-2">
          <span class="whight-text">
            <strong>Oops! Something went wrong.</strong>
          </span>
          <ul>
            <% @student.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
<% end%>

app/views/students/_studentsinfo.html.erb
<% @students.each do |student|%>
  <div class="col s6 m6">
    <div class="card blue-grey darken-1">
      <div class="card-content white-text">
        <span class="card-title"> <strong>Name: <%= student.name%></strong>  </span>
        <p>Email: <%= student.email%></p>
        <p>Course Enrollments: ....</p>
      </div>
      <div class="card-action">
        <%= link_to "View Profile", student_path(student) %>
      </div>
    </div>
  </div>
<% end%>

app/views/students/edit.html.erb
<%= render 'errormessages'%>
<div class="container sign-up ">
  <div class="row center ">
    <div class="col s12 m12 l12 card-panel">
      <h3 class=" header center-align">Edit your profile</h3>
      <%= form_for @student, html: { class: "col s12 " } do |f| %>
        <div class="row">
          <div class="input-field col s12 ">
            <i class="material-icons prefix">account_circle</i>
            <%= f.label :name, "Full Name", id: "full_name", class: "validate active" %>
            <%= f.text_field :name %>
          </div>
        </div>
        <div class="row">
          <div class="input-field col s12">
            <i class="material-icons prefix">email</i>
            <%= f.label :email, id: "email", class: "validate active" %>
            <%= f.email_field :email %>
          </div>
        </div>
        <div class="row">
          <div class="input-field col s12">
            <i class="material-icons prefix">lock</i>
            <%= f.label :password, id: "password", class: "validate" %>
            <%= f.password_field :password %>
          </div>
        </div>
        <div class="row">
          <div class="input-field col s12">
            <i class="material-icons prefix">lock</i>
            <%= f.label :password_confirmation, "Confirm Password", id: "password_confirmation", class: "validate" %>
            <%= f.password_field :password_confirmation %>
          </div>
        </div>
        <div class="row">
          <div class="input-field col s12 center-align">
            <%= f.submit "Submit changes", class: "btn waves-effect waves-light" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/students/index.html.erb
<div class="row">
  <div class="col s12">
    <h3 class="center-align" > Students Directroy</h3>
  </div>
</div>
<div class="row">
  <%= render 'studentsinfo'%>
</div>
<div class="row">
</div>
s

app/views/students/new.html.erb
<div class="row">
  <div class="col s12">
    <h3 class="center-align" > Sign up! </h3>
  </div>
</div>
<div class="row">
  <%= form_for @student, html: { class: "col s12  fstyle " } do |f| %>
    <div class="row">
      <div class="input-field col s7 offset-s3 mt-4">
        <i class="material-icons prefix">account_circle</i>
        <%= f.label :name, "Full Name", id: "full_name", class: "validate" %>
        <%= f.text_field :name %>
      </div>
    </div>
    <div class="row">
      <div class="input-field col s7 offset-s3 ">
        <i class="material-icons prefix">email</i>
        <%=  f.label :email,id:"email", class:"validate" %>
        <%= f.text_field :email  %>
      </div>
    </div>
    <div class="row">
      <div class="input-field col s7 offset-s3 center-align ">
        <%= f.submit "Submit", class: "btn waves-effect waves-light " %>
      </div>
    </div>
  <% end %>
</div>

app/views/students/show.html.erb
<div class="row">
  <div class="col s6 m6">
    <div class="card blue-grey darken-1">
      <div class="card-content white-text">
        <span class="card-title"> <strong>Name: <%= @student.name%></strong>  </span>
        <p>Email: <%= @student.email%></p>
        <p>Course Enrollments:
          <% if @student.courses.empty? %>
            None
          <% else %>
            <ul>
              <%  @student.courses.each do |course|%>
                <li> * <%=course.name%> </li>
              <%end%>
            </ul>
          <% end%>
        </p>
      </div>
    </div>
    <% if current_user == @student%>
      <%= link_to '<i class="material-icons left">create</i>Edit your profile'.html_safe, edit_student_path(@student),class:"waves-effect waves-light btn"%>
    <%end%>
  </div>
</div>